---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  become: true

- name: Start Vector service
  ansible.builtin.systemd:
    name: vector
    state: started
    enabled: true
  become: true